#' Retrieve datasources if not specified
#'
#' @param datasources An optional list of data sources. If not provided, the function will attempt
#' to find available data sources.
#' @return A list of data sources.
#' @noRd
.get_datasources <- function(datasources) {
  if (is.null(datasources)) {
    datasources <- datashield.connections_find()
    return(datasources)
  }
}

#' Verify that the provided data sources are of class 'DSConnection'.
#'
#' @param datasources A list of data sources.
#' @importFrom cli cli_abort
#' @noRd
.verify_datasources <- function(datasources) {
  is_connection_class <- datasources |> map_lgl(~ unlist(.x) |> methods::is("DSConnection"))
  if (!all(is_connection_class)) {
    cli_abort("The 'datasources' were expected to be a list of DSConnection-class objects")
  }
}

#' Set and verify data sources.
#'
#' @param datasources An optional list of data sources. If not provided, the function will attempt
#' to find available data sources.
#' @return A list of verified data sources.
#' @noRd
.set_datasources <- function(datasources) {
  datasources <- .get_datasources(datasources)
  .verify_datasources(datasources)
  return(datasources)
}


#' Set a new object or defaults to '.data' if no object is provided.
#'
#' @param newobj An optional new object name. If not provided, the function defaults to '.data'.
#' @return The provided new object name or '.data' if no object is provided.
#' @noRd
.set_new_obj <- function(.data, newobj) {
  if (is.null(newobj)) {
    newobj <- .data
  }
  return(newobj)
}

#' Check that the length of the character string provided to `.data` does not exceed the value of
#' nfilter.string
#'
#' @param .data The data object to be analyzed.
#' @param nfilter.string The maximum length of variable names allowed.
#' @importFrom stringr str_length
#' @noRd
.check_data_name_length <- function(.data, nfilter.string) {
  data_length <- str_length(.data)
  if (data_length > nfilter.string) {
    cli_abort(
      c("The length of string passed to `.data` must be less than {nfilter.string} characters.",
        "x" = "`.data` has a length of {data_length} characters."
      )
    )
  }
}

#' Generate an encoding key which is used for encoding and decoding strings to pass the R parser
#'
#' @return A list containing the encoding key, with 'input' specifying the characters to be encoded
#' and 'output' specifying their corresponding encoded values.
#' @noRd
.getEncodeKey <- function() {
  encode_list <- list(
    input = c("list", "(", ")", "\"", ",", " ", "c", ":", "!", "&", "|"),
    output = c("$LIST$", "$LB$", "$RB$", "$QUOTE$", "$COMMA$", "$SPACE$", "$C$", "$COLON$", "$EXCL$", "$AND$", "$OR$")
  )
  return(encode_list)
}

#' Remove List
#'
#' This function removes the 'list(' portion from a string.
#'
#' @param string A string containing the characters 'list('.
#' @return The string with 'list(' removed.
#' @importFrom stringr str_replace_all str_sub
#' @noRd
.remove_list <- function(string) {
  string |>
    str_replace_all(pattern = fixed("list("), replacement = "") |>
    str_sub(end = -2)
}

#' Converts expressions to a string and remove the 'list(' portion.
#'
#' @param expr The expression to be converted.
#' @return The formatted arguments as a string.
#' @importFrom rlang quo_text
#' @noRd
.format_args_as_string <- function(expr) {
  args_as_string <- quo_text(expr) ## Convert them to a string
  neat_args_as_string <- .remove_list(args_as_string)
  return(neat_args_as_string)
}

#' Encode a string using the provided encoding key.
#'
#' @param input_string The string to be encoded.
#' @param encode_key The encoding key generated by '.getEncodeKey()'.
#' @return The encoded string.
#' @importFrom stringr str_replace_all fixed
#' @importFrom rlang set_names
#' @noRd
.encode_tidy_eval <- function(input_string, encode_key) {
  encode_vec <- set_names(encode_key$output, encode_key$input)
  output_string <- str_replace_all(input_string, fixed(encode_vec))
}

#' Check if the functions used in tidy evaluation are permitted.
#'
#' @param args_as_string The string representation of the arguments.
#' @importFrom cli cli_abort
#' @importFrom stringr str_extract_all
#' @details To avoid users attempting to maliciously pass functions to the servervia the tidy_select
#' argument, a regex is used to first extract all functions from the string by identifying any characters
#' with the format 'name('. These are then checked against permitted arguments, which are selection
#' helpers described in the ?select documentation.#'
#' @noRd
.check_function_names <- function(args_as_string) {
  permitted_tidy_select <- c(
    "everything", "last_col", "group_cols", "starts_with", "ends_with", "contains",
    "matches", "num_range", "all_of", "any_of", "where"
  )

  function_names <- str_extract_all(args_as_string, "\\w+(?=\\()", simplify = T)
  any_banned_functions <- function_names[!function_names %in% permitted_tidy_select]
  if (length(any_banned_functions) > 0) {
    cli_abort(
      c(
        "`tidy_select` must only contain Tidyverse select functions",
        "x" = "You have included the following unpermitted function(s): '{any_banned_functions}'",
        "Search ?select for more information"
      )
    )
  }
}

#' Check if the length of variable names in tidy evaluation exceeds a nfilter.string threshold.
#'
#' @param args_as_string The string representation of the arguments.
#' @param nfilter.string The maximum length of variable names allowed.
#' @importFrom cli cli_abort
#' @importFrom stringr str_extract_all
#' @importFrom purrr map_int map_lgl
#' @details To check users are not passing variable names which are too long, first a regex extracts
#' variable names from the list passed to `tidy_select`. It then checks the lengths of these against
#' the value passed to nfilter.string.#'
#' @noRd
.check_variable_length <- function(args_as_string, nfilter.string) {
  variable_names <- str_extract_all(args_as_string, "\\b\\w+\\b(?!\\()", simplify = T)
  variable_lengths <- variable_names |> map_int(str_length)
  over_filter_thresh <- variable_lengths |> map_lgl(~ . > nfilter.string)
  too_long <- variable_names[over_filter_thresh]

  if (length(too_long) > 0) {
    cli_abort(
      c(
        "The maximum length of columns specified in `tidy_select` is {nfilter.string} characters.",
        "x" = "Detected {length(too_long)} variable{?s} longer than this: {too_long}"
      )
    )
  }
}

#' Checks both for length of variable names and names of functions passed to `tidy_args`
#'
#' @param args_as_string The string representation of the arguments.
#' @param nfilter.string The maximum length of variable names allowed.
#' @noRd
.tidy_disclosure_checks <- function(args_as_string, nfilter.string) {
  .check_function_names(args_as_string)
  .check_variable_length(args_as_string, nfilter.string)
}

